# Generated by Django 4.2 on 2025-09-20 18:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('branches', '0002_branchmedicationbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Código único do lote em todo o sistema', max_length=50, unique=True, verbose_name='Número do Lote')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('expiry_date', models.DateField(help_text='Data única válida em todo o sistema', verbose_name='Data de Vencimento')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Compra')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência do Fornecedor')),
                ('initial_quantity', models.PositiveIntegerField(help_text='Quantidade total produzida neste lote', verbose_name='Quantidade Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lote Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_batches', to='inventory.medication', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento (Unificado)',
                'verbose_name_plural': 'Lotes de Medicamentos (Unificados)',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='BatchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('general', 'Estoque Geral'), ('branch', 'Filial')], max_length=20, verbose_name='Tipo de Local')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade no Local')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade Reservada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Localização Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.medicationbatch', verbose_name='Lote')),
                ('branch', models.ForeignKey(blank=True, help_text='NULL para estoque geral', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Localização do Lote',
                'verbose_name_plural': 'Localizações dos Lotes',
                'ordering': ['batch__expiry_date', 'batch__batch_number'],
                'unique_together': {('batch', 'location_type', 'branch')},
            },
        ),
    ]
