# Generated by Django 4.2 on 2025-09-19 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('estoque', 'Relatório de Estoque'), ('movimentacao', 'Relatório de Movimentação'), ('vencimento', 'Relatório de Vencimentos'), ('vendas', 'Relatório de Vendas'), ('fornecedores', 'Relatório de Fornecedores')], max_length=20, verbose_name='Tipo de Relatório')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Arquivo')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
    ]
