# Generated by Django 4.2 on 2025-09-20 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Filial Centro, Filial Shopping, etc.', max_length=200, verbose_name='Nome da Filial')),
                ('code', models.CharField(help_text='Código único da filial (ex: FIL001)', max_length=10, unique=True, verbose_name='Código da Filial')),
                ('address', models.TextField(verbose_name='Endereço Completo')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Até 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail da Filial')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Receber notificações por email')),
                ('whatsapp_notifications', models.BooleanField(default=False, verbose_name='Receber notificações por WhatsApp')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Formato: +5511999999999', max_length=20, null=True, verbose_name='Número WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Filial Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Gerente Responsável')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_transit', 'Em Trânsito'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(help_text='Descreva o motivo da transferência', verbose_name='Motivo da Transferência')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='branches.branch', verbose_name='Filial Origem')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication', verbose_name='Medicamento')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='branches.branch', verbose_name='Filial Destino')),
            ],
            options={
                'verbose_name': 'Transferência de Estoque',
                'verbose_name_plural': 'Transferências de Estoque',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Medicamentos reservados para vendas', verbose_name='Quantidade Reservada')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='branches.branch', verbose_name='Filial')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Estoque por Filial',
                'verbose_name_plural': 'Estoques por Filial',
                'ordering': ['branch', 'medication__name'],
                'unique_together': {('branch', 'medication')},
            },
        ),
    ]
