# Generated by Django 4.2 on 2025-09-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMedicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Número do Lote')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade do Lote')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('expiry_date', models.DateField(verbose_name='Data de Vencimento')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Compra')),
                ('supplier_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência do Fornecedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lote Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('branch_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='branches.branchstock', verbose_name='Estoque da Filial')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Lotes de Medicamentos',
                'ordering': ['expiry_date', 'batch_number'],
                'unique_together': {('branch_stock', 'batch_number')},
            },
        ),
    ]
