# Generated by Django 4.2 on 2025-09-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('template_type', models.CharField(choices=[('low_stock', 'Estoque Baixo'), ('expiry_alert', 'Vencimento Próximo'), ('expired_medication', 'Medicamento Vencido'), ('transfer_request', 'Solicitação de Transferência'), ('transfer_completed', 'Transferência Concluída'), ('daily_report', 'Relatório Diário')], max_length=20, verbose_name='Tipo de Template')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto do E-mail')),
                ('email_body', models.TextField(help_text='Use {{variavel}} para dados dinâmicos', verbose_name='Corpo do E-mail (HTML)')),
                ('whatsapp_message', models.TextField(blank=True, help_text='Use {{variavel}} para dados dinâmicos', null=True, verbose_name='Mensagem WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Template Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Destinatário')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Destinatário')),
                ('notification_type', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10, verbose_name='Tipo de Notificação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('delivered', 'Entregue')], default='pending', max_length=10, verbose_name='Status')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem Enviada')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Filial')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Template Usado')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-sent_at'],
            },
        ),
    ]
